# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'epx11c' do
	pod 'SDCAlertView'
    	pod ‘Firebase/Core’
    	pod ‘Firebase/AdMob’
    	pod 'Firebase/Core'
end

